name: Run test matrix

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        debug-buildConfiguration: [debug]
        release-buildConfiguration: [release]

    steps:
    - name: Git checkout
      uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.debug-buildConfiguration }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.debug-buildConfiguration }}

    - name: Start MongoDB v${{ release-buildConfiguration }}
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ release-buildConfiguration }}
      if: and(success(),eq(${{ matrix.debug-buildConfiguration }}, 'release'))
        
    - run: echo "done"
